# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements:
        - sphinx>=9.0.4
        - sphinx-rtd-theme>=3.0.2
        - sphinx-autodoc-typehints>=2.5.0
        - sphinx-rtd-dark-mode>=1.3.0
