version: 2
formats: []

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: docs/source/requirements.txt
